/* ==========================================================
   AMAZON SALES SQL PROJECT
   Script: 03_intermediate_queries.sql
   Level : INTERMEDIATE SQL
   DB    : database/amazon_sales.db  (SQLite)

   Tables:
     dim_category (category_id, category_name)
     dim_region   (region_id, region_name)
     dim_payment  (payment_id, payment_method)
     fact_orders  (order_id, order_date, product_id, category_id,
                   price, discount_percent, quantity_sold,
                   region_id, payment_id, rating, review_count,
                   discounted_price, total_revenue)

   This script is organized into sections. Each query has a
   short business question as a comment above it. Concepts
   covered: multi-table JOINs, GROUP BY / HAVING, subqueries
   (scalar + correlated), CTEs, CASE expressions, date & string
   functions, basic window functions, UNION, and views.
   ========================================================== */


/* ----------------------------------------------------------
   SECTION 1: JOINS
   ---------------------------------------------------------- */

-- Q1. List the first 10 orders with their category, region and
--     payment method names instead of raw IDs (INNER JOIN across
--     3 dimension tables).
SELECT
    f.order_id,
    f.order_date,
    c.category_name,
    r.region_name,
    p.payment_method,
    f.total_revenue
FROM fact_orders f
JOIN dim_category c ON f.category_id = c.category_id
JOIN dim_region   r ON f.region_id   = r.region_id
JOIN dim_payment  p ON f.payment_id  = p.payment_id
ORDER BY f.order_id
LIMIT 10;

-- Q2. Total revenue generated by each product category, sorted
--     from highest to lowest (JOIN + GROUP BY).
SELECT
    c.category_name,
    ROUND(SUM(f.total_revenue), 2) AS total_revenue,
    COUNT(*) AS number_of_orders
FROM fact_orders f
JOIN dim_category c ON f.category_id = c.category_id
GROUP BY c.category_name
ORDER BY total_revenue DESC;

-- Q3. Which payment method is most popular in each region?
--     (JOIN + GROUP BY on two dimensions together)
SELECT
    r.region_name,
    p.payment_method,
    COUNT(*) AS order_count
FROM fact_orders f
JOIN dim_region  r ON f.region_id  = r.region_id
JOIN dim_payment p ON f.payment_id = p.payment_id
GROUP BY r.region_name, p.payment_method
ORDER BY r.region_name, order_count DESC;


/* ----------------------------------------------------------
   SECTION 2: GROUP BY / HAVING / AGGREGATE FUNCTIONS
   ---------------------------------------------------------- */

-- Q4. Find categories where average customer rating is below 3.5
--     (aggregate + HAVING, a filter that runs AFTER grouping).
SELECT
    c.category_name,
    ROUND(AVG(f.rating), 2) AS avg_rating,
    COUNT(*) AS total_orders
FROM fact_orders f
JOIN dim_category c ON f.category_id = c.category_id
GROUP BY c.category_name
HAVING AVG(f.rating) < 3.5
ORDER BY avg_rating;

-- Q5. Monthly order volume and revenue trend for 2023
--     (date functions + GROUP BY on a derived column).
SELECT
    strftime('%Y-%m', order_date) AS order_month,
    COUNT(*) AS orders,
    ROUND(SUM(total_revenue), 2) AS monthly_revenue
FROM fact_orders
WHERE strftime('%Y', order_date) = '2023'
GROUP BY order_month
ORDER BY order_month;

-- Q6. Regions where total quantity sold exceeds 20,000 units
--     (HAVING on SUM).
SELECT
    r.region_name,
    SUM(f.quantity_sold) AS total_units_sold
FROM fact_orders f
JOIN dim_region r ON f.region_id = r.region_id
GROUP BY r.region_name
HAVING SUM(f.quantity_sold) > 20000
ORDER BY total_units_sold DESC;


/* ----------------------------------------------------------
   SECTION 3: SUBQUERIES
   ---------------------------------------------------------- */

-- Q7. Find all orders whose total_revenue is above the overall
--     average total_revenue (scalar subquery in WHERE clause).
SELECT order_id, order_date, total_revenue
FROM fact_orders
WHERE total_revenue > (SELECT AVG(total_revenue) FROM fact_orders)
ORDER BY total_revenue DESC
LIMIT 20;

-- Q8. For every category, show orders that earned more revenue
--     than that category's own average revenue (CORRELATED
--     subquery -- the inner query re-runs per outer row).
SELECT
    f.order_id,
    c.category_name,
    f.total_revenue
FROM fact_orders f
JOIN dim_category c ON f.category_id = c.category_id
WHERE f.total_revenue > (
    SELECT AVG(f2.total_revenue)
    FROM fact_orders f2
    WHERE f2.category_id = f.category_id
)
ORDER BY c.category_name, f.total_revenue DESC
LIMIT 30;

-- Q9. List categories that have NEVER been paid for using
--     'Cash on Delivery' (subquery with NOT IN).
SELECT category_name
FROM dim_category
WHERE category_id NOT IN (
    SELECT DISTINCT f.category_id
    FROM fact_orders f
    JOIN dim_payment p ON f.payment_id = p.payment_id
    WHERE p.payment_method = 'Cash on Delivery'
);
-- (Expect an empty result here if every category has at least one COD order --
--  try changing the payment method above to test the logic.)


/* ----------------------------------------------------------
   SECTION 4: CTEs (WITH clause)
   ---------------------------------------------------------- */

-- Q10. Use a CTE to first compute revenue per category, then
--      rank the categories by revenue in the outer query.
WITH category_revenue AS (
    SELECT
        c.category_name,
        SUM(f.total_revenue) AS revenue
    FROM fact_orders f
    JOIN dim_category c ON f.category_id = c.category_id
    GROUP BY c.category_name
)
SELECT
    category_name,
    ROUND(revenue, 2) AS revenue,
    ROUND(100.0 * revenue / (SELECT SUM(revenue) FROM category_revenue), 2) AS pct_of_total_revenue
FROM category_revenue
ORDER BY revenue DESC;

-- Q11. Two CTEs chained together: first find each region's
--      average discount, then flag regions that discount more
--      heavily than the company-wide average.
WITH region_discount AS (
    SELECT
        r.region_name,
        AVG(f.discount_percent) AS avg_discount
    FROM fact_orders f
    JOIN dim_region r ON f.region_id = r.region_id
    GROUP BY r.region_name
),
overall_avg AS (
    SELECT AVG(discount_percent) AS company_avg_discount
    FROM fact_orders
)
SELECT
    rd.region_name,
    ROUND(rd.avg_discount, 2) AS avg_discount,
    ROUND(oa.company_avg_discount, 2) AS company_avg_discount,
    CASE
        WHEN rd.avg_discount > oa.company_avg_discount THEN 'Above Average'
        ELSE 'At or Below Average'
    END AS discount_flag
FROM region_discount rd
CROSS JOIN overall_avg oa
ORDER BY avg_discount DESC;


/* ----------------------------------------------------------
   SECTION 5: CASE EXPRESSIONS
   ---------------------------------------------------------- */

-- Q12. Bucket every order into a revenue tier, then count how
--      many orders fall into each tier.
SELECT
    CASE
        WHEN total_revenue < 200       THEN 'Low ( < 200 )'
        WHEN total_revenue < 800       THEN 'Medium ( 200 - 799 )'
        WHEN total_revenue < 2000      THEN 'High ( 800 - 1999 )'
        ELSE 'Premium ( 2000+ )'
    END AS revenue_tier,
    COUNT(*) AS order_count,
    ROUND(SUM(total_revenue), 2) AS tier_revenue
FROM fact_orders
GROUP BY revenue_tier
ORDER BY tier_revenue DESC;

-- Q13. Classify each order's discount level and show the
--      average rating customers gave at each discount level.
SELECT
    CASE
        WHEN discount_percent = 0            THEN 'No Discount'
        WHEN discount_percent BETWEEN 1 AND 10  THEN 'Small Discount (1-10%)'
        WHEN discount_percent BETWEEN 11 AND 25 THEN 'Medium Discount (11-25%)'
        ELSE 'Large Discount (25%+)'
    END AS discount_bucket,
    COUNT(*) AS orders,
    ROUND(AVG(rating), 2) AS avg_rating
FROM fact_orders
GROUP BY discount_bucket
ORDER BY orders DESC;


/* ----------------------------------------------------------
   SECTION 6: WINDOW FUNCTIONS (intro-level)
   ---------------------------------------------------------- */

-- Q14. Rank categories by total revenue using RANK() (window
--      function replaces a manual self-join / subquery approach).
SELECT
    category_name,
    revenue,
    RANK() OVER (ORDER BY revenue DESC) AS revenue_rank
FROM (
    SELECT c.category_name, SUM(f.total_revenue) AS revenue
    FROM fact_orders f
    JOIN dim_category c ON f.category_id = c.category_id
    GROUP BY c.category_name
) AS cat_totals;

-- Q15. Running total of daily revenue across January 2023
--      (window function with ORDER BY, no PARTITION BY).
SELECT
    order_date,
    ROUND(SUM(total_revenue), 2) AS daily_revenue,
    ROUND(SUM(SUM(total_revenue)) OVER (ORDER BY order_date), 2) AS running_total_revenue
FROM fact_orders
WHERE order_date BETWEEN '2023-01-01' AND '2023-01-31'
GROUP BY order_date
ORDER BY order_date;

-- Q16. For each category, number the orders from most to least
--      recent using ROW_NUMBER() PARTITION BY, then keep only
--      each category's 3 most recent orders.
SELECT category_name, order_id, order_date, total_revenue
FROM (
    SELECT
        c.category_name,
        f.order_id,
        f.order_date,
        f.total_revenue,
        ROW_NUMBER() OVER (
            PARTITION BY c.category_name
            ORDER BY f.order_date DESC
        ) AS rn
    FROM fact_orders f
    JOIN dim_category c ON f.category_id = c.category_id
) ranked
WHERE rn <= 3
ORDER BY category_name, order_date DESC;


/* ----------------------------------------------------------
   SECTION 7: UNION / SET OPERATIONS
   ---------------------------------------------------------- */

-- Q17. Combine a list of "top revenue" categories and "top
--      rated" categories into a single watch-list, removing
--      duplicates (UNION).
SELECT category_name, 'Top Revenue' AS reason
FROM (
    SELECT c.category_name, SUM(f.total_revenue) AS revenue
    FROM fact_orders f JOIN dim_category c ON f.category_id = c.category_id
    GROUP BY c.category_name
    ORDER BY revenue DESC
    LIMIT 3
)
UNION
SELECT category_name, 'Top Rated' AS reason
FROM (
    SELECT c.category_name, AVG(f.rating) AS avg_rating
    FROM fact_orders f JOIN dim_category c ON f.category_id = c.category_id
    GROUP BY c.category_name
    ORDER BY avg_rating DESC
    LIMIT 3
);


/* ----------------------------------------------------------
   SECTION 8: VIEWS
   ---------------------------------------------------------- */

-- Q18. Create a reusable view that pre-joins the fact table with
--      all three dimensions, so future analysts can query plain
--      column names without repeating the JOINs every time.
DROP VIEW IF EXISTS vw_orders_full;
CREATE VIEW vw_orders_full AS
SELECT
    f.order_id,
    f.order_date,
    f.product_id,
    c.category_name,
    f.price,
    f.discount_percent,
    f.discounted_price,
    f.quantity_sold,
    r.region_name,
    p.payment_method,
    f.rating,
    f.review_count,
    f.total_revenue
FROM fact_orders f
JOIN dim_category c ON f.category_id = c.category_id
JOIN dim_region   r ON f.region_id   = r.region_id
JOIN dim_payment  p ON f.payment_id  = p.payment_id;

-- Example usage of the view: top 5 highest revenue orders in Asia
SELECT order_id, order_date, category_name, region_name, total_revenue
FROM vw_orders_full
WHERE region_name = 'Asia'
ORDER BY total_revenue DESC
LIMIT 5;

/* ==========================================================
   END OF SCRIPT
   ========================================================== */
